### ISSUE TITLE
SM76X USB Linux Drivers?

### ISSUE THREAD

**Issue by papag00se** [teddywlq/smifb2#3]
Very sorry to create an issue and annoy you, but you seem to be the only person on the Internet that has any information about this. I saw you answered another person by saying that there are USB drivers for Linux for the SM76X. The only drivers that the manufacturer links to are the Silicon Motion drivers here: https://www.siliconmotion.com/downloads/index.html, which don't have Linux.

Do you know where USB Linux drivers are for SM76X? You would make a lot of people happy if you did.

**Comment by lando07** [comment]
Hey @papag00se I've actually discussed the same thing with teddy, and he sadly cannot help in our case, but I do have a solution. I've contacted Silicon Motion about a Linux USB driver, and they are currently working on it. It was scheduled to release parallel with ubuntu 22.04, however, however it is still in beta. After asking them if I could test out the beta driver, they gave me the install file for it. Because it is still in beta, and I talked directly to them, I don't feel comfortable sharing the files, as this beta driver isn't available on their website. It is under development right now, and hopefully, it will come out soon. As I am driving the beta driver daily, it is working out with great success, but there is still about a 0.1-second frame buffer/input lag and doesn't support night light or things like the windows driver. I apologize I can't help, but that is the current state.

**Comment by papag00se** [comment]
THIS IS AWESOME! So happy. I am a software engineer and have been dabbling across different Linux distros for years. If and when Silicon Motion or yourself wants someone to test these drivers, I would be very happy to do so.

Thank you! How can I check back on this later? I feel bad that I created an open issue.

**Comment by ahmed-jibran** [comment]
@papag00se @lando07  I am also looking for Ubuntu usb drivers for SM76x, by any chance, if you can share it ? Or point me to source code so I can compile it, My discord is jahmed#3398
